version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/  # Скопируем конфигурацию Prometheus
      - prometheus-data:/prometheus  # Данные Prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"  # Порт Prometheus

  app_a:
    image: apppubsub:master
    build: .
    container_name: app_a
    entrypoint: ["python", "app_a.py"]
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    volumes:
      - ./code:/code

  app_b:
    image: apppubsub:master
    build: .
    container_name: app_b
    entrypoint: ["python", "app_b.py"]
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"  # Порт приложения Б
    volumes:
      - ./code:/code

  source_app:
    image: apppubsub:master
    build: .
    container_name: source_app
    entrypoint: ["python", "source_app.py"]
    environment:
      - RATE_PER_SECOND=50  # Можно менять по своему усмотрению
    depends_on:
      - app_a
    ports:
      - "5001:5001"  # Порт источника запросов
    volumes:
      - ./code:/code

volumes:
  prometheus-data: