global:
  scrape_interval: 10s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'app-a-metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['app_a:8000']

  - job_name: 'app-b-metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['app_b:5000']

  - job_name: 'source-app-metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['source_app:5001']

  - job_name: 'rabbitmq-server'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'rabbitmq:15692'