{
 "title": "Мониторинг приложений",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Панель мониторинга", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Затраченное время на отправку сообщения из приложения А в RabbitMQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_a_response_time_histogram_bucket[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Время выполнения операции сложения в приложении Б",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_b_processing_time_histogram_bucket[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Среднее время отклика приложения А",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(source_response_time_histogram_bucket[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Среднее время обработки в приложении Б",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_b_processing_time_histogram_bucket[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Количество запросов в приложении А",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(app_a_request_count[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Количество обработанных сообщений в приложении Б",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(app_b_message_processing_count[$__rate_interval]))"
    }
   ]
  }
 ]
}